parameters:

    #
    # Services
    #
    store.payment.service.payment_bridge.class: Elcodi\Store\PaymentBridgeBundle\Services\PaymentBridge

    #
    # Event Listeners
    #
    store.payment.event_listener.payment.class: Elcodi\Store\PaymentBridgeBundle\EventListener\PaymentEventListener
