Elcodi\PaymentBridgeBundle\Entity\PaypalTransaction:
    type: entity
    repositoryClass: Elcodi\PaymentBridgeBundle\Repository\PaypalTransactionRepository
    table: paypal_transaction
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        transaction:
            column: transaction
            type: string
        ordered:
            column: ordered
            type: boolean
            nullable: false
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    manyToOne:
        customer:
            targetEntity: Elcodi\Component\Cart\Entity\Order
            joinColumn:
                name: order_id
                referencedColumnName: id
                nullable: false
                onDelete: "SET NULL"

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
