services:

    #
    # Event Listeners
    #
    store.user.event_listener.remember_password:
        class: %store.user.event_listener.remember_password.class%
        arguments:
            - @security.context
        tags:
            - { name: kernel.event_listener, event: password.recover, method: onPasswordRecover }
